name: "Tests"

on:
  pull_request:
  push:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: cachix/install-nix-action@v22
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Run tests
      run: |
        nix-shell --command "fish -c '\
          curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source && fisher install jorgebucaran/fisher;\
          fisher install jorgebucaran/fishtape;\
          make test | tee results.tap'"

    - name: Test Summary
      uses: pcolby/tap-summary@v1
      with:
        path: >-
          results.tap
