name: "Tests"

on:
  pull_request:
  push:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - uses: cachix/install-nix-action@v22
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    
    - run: |
        curl -O 'https://raw.githubusercontent.com/fisherman/fishtape/master/fishtape.fish'
        nix-shell --command "fish -c 'source fishtape.fish; make test'"
